### ISSUE TITLE
Doof

### ISSUE THREAD

**Issue by Rogasch** [CC1337/LEDDisplay#18]
Implementiere einen "Ich bin Doof" Getter zum anzeigen auf dem Display bei jedem 2. Frame

**Comment by Rogasch** [comment]
immernoch doof

**Comment by CC1337** [comment]
![original-and-timelapse](https://user-images.githubusercontent.com/4866744/42181748-3fcdbfd4-7e3c-11e8-90f7-544155c8344a.gif)
